### ISSUE TITLE
「お知らせ」へのリンクが404 Not Found

### ISSUE THREAD

**Issue by sasigume** [kanji1113/Kuromaru.ml#8]
blogディレクトリは使ってないようだけど、直し方がわからない。何か記事を書いてデフォルトの記事と入れ替えるべきでは？

**Comment by kanji1113** [comment]
設定を後回しにしていました。
工事中エントリーを作成したので解消しました。
ご指摘ありがとうございました。

**Comment by kanji1113** [comment]
ご指摘ありがとうございました、仮ページ配置で解消しました。
